ADD: Expenses - backend, frontend, and tests

diff --git a/webclient/Makefile b/webclient/Makefile
--- a/webclient/Makefile
+++ b/webclient/Makefile
@@ -3,6 +3,15 @@ BINDIR=${TOP}/tmp/rentroll
 
 webclient:
 	@touch fail
+	if [ ! -d node_modules ]; then \
+		echo "node_modules does not exits.  Will attempt to create..."; \
+		sh -c "ln -s `npm root -g`"; \
+	fi ;\
+	if [ ! -d node_modules ]; then \
+		echo "Could not make node_modules directory" ;\
+		exit 1 ;\
+	fi
+	
 	grunt clean
 	mkdir -p ./temp
 	grunt
